services:
  server:
    image: <NAME>/fedscope_server:latest
    container_name: server
    network_mode: host
    healthcheck:  #for guarantee that the clients start after the server
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/8080"]
      interval: 5s
      retries: 5
    command: ["--round", "5", "--client_number", "1","--server_port","8080", "--max_voc_size", "500", "--beta", "800"]
    volumes:
      - ./docker_result/log:/fedscope/log
      - ./docker_result/interess:/fedscope/interess
      - ./docker_result/model:/fedscope/models
      - ./docker_result/vocabulary:/fedscope/vocabularies


  client1:
    image: <NAME>/fedscope_client:latest
    container_name: client1
    network_mode: host
    depends_on:
      server:
        condition: service_healthy
    command: ["--cid","1"]
    volumes:
      - ../dataset/darknet01/:/fedscope/dataset/darknet01/
      - ./docker_result/log:/fedscope/log



 # client2:
 #   image: <NAME>/fedscope_client:latest
 #   container_name: client2
 #   network_mode: host
 #   depends_on:
 #     server:
 #       condition: service_healthy
 #   command: ["--cid","2"]
 #   volumes:
 #     - ../dataset/darknet02/:/fedscope/dataset/darknet02/
 #     - ./docker_result/log:/fedscope/log
