trainer:
  train_data_pth: [
    ../traffic_data/mawi/flow/202306.pcap.pkl
  ]
  test_data_pth: [
    ../traffic_data/mawi/flow/test.pkl
  ]

  load_save_pth: ../pretrained_models/56_bi_attn_linear/BERTLM_model_mawi202306_sizebest.pth
  timevocab_pth: ./trafficMimic/dataset/timevocab_56.pkl
  sizevocab_pth: ./trafficMimic/dataset/sizevocab_1606.pkl
  model_save_pth: ../pretrained_models/56_bi_attn_linear/BERTLM_model_mawi202306_sizebest.pth
  device: 0
  batch_size: 64
  epochs: 300
  log_frequency: 10
  optimizer:
    type: 'AdamW'
    lr: 0.001
    beta: (0.9, 0.999)
    weight_decay: 0.01
    warmup_steps: 10000


model:
  seq_len: 512
  f_features: 2
  hidden: 128
  d_ff: 512
  n_layers: 6
  attn_heads: 8
  dropout: 0.1