[package]
name = "cellshift"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib/mod.rs"

[dependencies]
anyhow = "1.0.0"
clap = { version = "4.5.0", features = ["derive"] }
clap-num = "1.2.0"
env_logger = "0.11.0"
gtt23 = { git = "https://github.com/robgjansen/gtt23.git", version = "0.1.0" }
hdf5 = { package = "hdf5-metno", version = "0.10.0", features = ["blosc-zstd"] }
humantime = "2.2.0"
indicatif = "0.17.0"
log = "0.4.0"
ndarray = "0.16.0"
rand = "0.9.0"
rand_chacha = "0.9.0"
serde_json = "1.0.0"
uuid = { version = "1.16.0", features = ["v4", "fast-rng"] }
zstd = "0.13.0"
