project_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS
code_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/source/HFT-MGBS
datasets_root: /opt/data/private/wangwt/ParkAttackKE/datasets
feature_cache_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/features
models_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/models
runs_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/runs
results_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/results
profiles_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/profiles
manifests_root: /opt/data/private/wangwt/ParkAttackKE/HFT-MGBS/manifests
