import numpy as np
from flwr.common.logger import log
from logging import DEBUG, ERROR, INFO, WARN

# the vocabulary will be automatically generated by gensim,
# but here we have to build manually for pytorch
def gen_vocabs(corpus):
    vocab = set([word for sentence in corpus for word in sentence])
    
    vocab = sorted(list(vocab))
    word_to_ind = {word: ind for ind, word in enumerate(vocab)}
    vocab = set(vocab)
    
    # ind_to_word = {ind: word for ind, word in enumerate(vocab)} # not needed for now
    return vocab, word_to_ind


def gen_training_pairs(corpus, context_window_size=5):
    """
    Generate training samples from the corpus
    :param corpus: a list of lists of IPs
    :param context_window_size: size of the context window
    :return: training_pairs: a list of tuples of the form (target, context)
    """
    training_pairs = []
    for sentence in corpus:
        for i in range(len(sentence)):
            for j in range(max(0, i - context_window_size), min(len(sentence), i + context_window_size + 1)):
                if i != j:
                    training_pairs.append((sentence[i], sentence[j]))
    return training_pairs


def gen_ns_table(pairs, t=60, power_parameter=0.75, ns_table_size=2**24):
    """
    pairs - pairs of entities. Probably (ip_source,ip_destination) in our real data.
    t - threshold variable from the paper.
    power_parameter - exponent used to shape the negative sampling distribution, defined as 0.75 in the original Word2Vec paper.
    ns_table_size - size of the negative sampling table.
    """
    from collections import Counter
    import operator

    flat_list_of_pairs = [item for sublist in pairs for item in sublist]
    counter = Counter(flat_list_of_pairs)
   
    # replace all the counts for cases where #.times of appearence < t --> 0
    increasingly_sorted_counter = dict(sorted(counter.items(), key=operator.itemgetter(1)))
    increasingly_sorted_counter_keys = list(increasingly_sorted_counter.keys())
    increasingly_sorted_counter_values = np.array(list(increasingly_sorted_counter.values()))
    increasingly_sorted_counter_values[increasingly_sorted_counter_values < t] = 0
    increasingly_sorted_counter_thresholded = {i: j for i, j in zip(increasingly_sorted_counter_keys,
                                                                    increasingly_sorted_counter_values)}
    decreasingly_sorted_counter_thresholded = dict(
        sorted(increasingly_sorted_counter_thresholded.items(), key=operator.itemgetter(1), reverse=True))

    # convert to frequencies rather than counts
    # S = np.sum(np.array(list(decreasingly_sorted_counter_thresholded.values())))
    S = 1
    decreasingly_sorted_counter_thresholded_freq_values = [decreasingly_sorted_counter_thresholded[k] / S for k in
                                                           decreasingly_sorted_counter_thresholded.keys()]
    decreasingly_sorted_counter_thresholded_keys = list(decreasingly_sorted_counter_thresholded.keys())

    # Create negative_sampling table
    # The negative sampling probabilities are proportional to the frequencies
    # to the power of a constant (typically 0.75).
    freqs_sorted = [
        (decreasingly_sorted_counter_thresholded_keys[j], decreasingly_sorted_counter_thresholded_freq_values[j]) for j
        in range(len(decreasingly_sorted_counter_thresholded_keys))]
    ns_table = {}
    sum_freq = 0
    for w, freq in freqs_sorted:
        ns_freq = freq ** power_parameter
        ns_table[w] = ns_freq
        sum_freq += ns_freq
    

    # Convert the negative sampling probabilities to integers, in order to make
    # sampling a bit faster and easier.
    # We return a list of tuples consisting of:
    # - the word
    # - its frequency in the training data
    # - the number of positions reserved for this word in the negative sampling table
    scaler = ns_table_size / sum_freq
    results = [(w, freq, int(round(ns_table[w] * scaler))) for w, freq in freqs_sorted]
    return results


class ContextGenerator:
    def __init__(self, ns_table, k=20):

        # Cerate a repeated list of negative samples, using ns_table
        unflattened_list = [[x[0]] * x[2] for x in ns_table]
        flattened_list = np.array([item for sublist in unflattened_list for item in sublist])
        self.ns_table = flattened_list
        self.k = k

    def create_batch(self, true_pairs):
        """
        Create a batch of examples to be entered later to the darkvec model.
        - pairs_batch: a list of true pairs, containing pairs of entities like [(ip1,ip2)(ip1,ip3),...].
        - ns_table: A list of different entities from the data, with their empirical
          probabilities, and with the number of times they are to repeat in the table
          that we will train on.

        stages:
        1. Given desired number of examples:
          - Sample alpha in [1, int(theta*<batch_size>)] to make the number of true
            pairs in the batch. The rest of the sample [int(0.25*<batch_size>), (<batch_size>-1)]
            will be the false pairs to be generated.
          - Draw <alpha> number of obs from pairs
          - Draw (<batch_size>-<alpha>) ip addresses from ns_table.
          - Choose with replacement ip addresses from the true pairs and assign them with
            new destinations.

        """

        # unpack from self
        ns_table = self.ns_table
        k = self.k
        batch_size = len(true_pairs)

        # define resulting_batch
        resulting_batch = []

        # add positive pairs to batch
        for pair in true_pairs:
            resulting_batch.append([pair[0], pair[1], 1])

        # keep only sources
        sources = [x[0] for x in true_pairs]

        # Draw batch_size-alpha false entities
        false_entities = np.random.choice(ns_table, size=(k * batch_size))

        pair_indexes = np.random.randint(1, len(sources), size=len(false_entities))

        # add negative pairs to batch
        for j in range(len(false_entities)):
            resulting_batch.append([sources[pair_indexes[j]], false_entities[j], 0])

        return np.array(resulting_batch)
